# Generated by Django 5.0.3 on 2024-03-24 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0004_kniha_vydavatelstvi_alter_kniha_pocet_stran_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recenze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Vložte text recenze', verbose_name='Text recenze')),
                ('hodnoceni', models.PositiveSmallIntegerField(choices=[(0, ''), (1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=3, verbose_name='Hodnocení')),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('kniha', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='knihovna.kniha', verbose_name='Kniha')),
                ('recenzent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Recenzent')),
            ],
        ),
    ]
