# Generated by Django 5.2.11 on 2026-03-04 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0004_kniha_vydavatelstvi_alter_kniha_pocet_stran_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recenze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(error_messages={'blank': 'Text recenze je povinný'}, help_text='Napište text recenze', verbose_name='Text recenze')),
                ('hodnoceni', models.IntegerField(choices=[(0, '☆☆☆☆☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=3, help_text='Vyberte hodnocení od 0 do 5', verbose_name='Hodnocení')),
                ('upraveno', models.DateTimeField(auto_now=True, help_text='Datum poslední úpravy se nastavuje automaticky', verbose_name='Naposledy upraveno')),
                ('kniha', models.ForeignKey(error_messages={'blank': 'Kniha musí být vybrána'}, help_text='Vyberte recenzovanou knihu', on_delete=django.db.models.deletion.CASCADE, related_name='recenze', to='knihovna.kniha', verbose_name='Kniha')),
                ('recenzent', models.ForeignKey(error_messages={'blank': 'Recenzent musí být vybrán'}, help_text='Vyberte recenzenta', on_delete=django.db.models.deletion.CASCADE, related_name='recenze', to='knihovna.autor', verbose_name='Recenzent')),
            ],
            options={
                'verbose_name': 'Recenze',
                'verbose_name_plural': 'Recenze',
                'ordering': ['-hodnoceni'],
            },
        ),
    ]
