# Generated by Django 5.0.3 on 2024-05-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0005_recenze'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recenze',
            options={'ordering': ['-hodnoceni'], 'verbose_name': 'Recenze', 'verbose_name_plural': 'Recenze'},
        ),
    ]
