# Generated by Django 5.2.11 on 2026-03-04 20:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0005_recenze'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vypujcka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctenar', models.CharField(error_messages={'blank': 'Čtenář musí být vyplněn.'}, help_text='Zadejte jméno a příjmení čtenáře.', max_length=120, verbose_name='Čtenář')),
                ('datum_vypujcky', models.DateField(default=django.utils.timezone.localdate, help_text='Datum, kdy byla kniha zapůjčena.', verbose_name='Datum výpůjčky')),
                ('termin_vraceni', models.DateField(error_messages={'blank': 'Termín vrácení je povinný.'}, help_text='Nejzazší datum, do kdy má být kniha vrácena.', verbose_name='Termín vrácení')),
                ('stav', models.CharField(choices=[('vypujceno', 'Vypůjčeno'), ('vraceno', 'Vráceno'), ('po_terminu', 'Po termínu')], default='vypujceno', help_text='Aktuální stav výpůjčky.', max_length=20, verbose_name='Stav výpůjčky')),
                ('poznamka', models.TextField(blank=True, help_text='Volitelná poznámka (poškození, domluva o prodloužení, ...).', verbose_name='Poznámka')),
                ('upraveno', models.DateTimeField(auto_now=True, verbose_name='Naposledy upraveno')),
                ('kniha', models.ForeignKey(help_text='Vyberte knihu, která je půjčená.', on_delete=django.db.models.deletion.CASCADE, related_name='vypujcky', to='knihovna.kniha', verbose_name='Kniha')),
            ],
            options={
                'verbose_name': 'Výpůjčka',
                'verbose_name_plural': 'Výpůjčky',
                'ordering': ['-datum_vypujcky', 'termin_vraceni'],
            },
        ),
    ]
