# Generated by Django 5.0.3 on 2024-03-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0005_recenze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenze',
            name='upraveno',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
