# Generated by Django 5.2.11 on 2026-03-04 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0007_recenze_recenzent_to_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenze',
            name='recenzent',
            field=models.ForeignKey(error_messages={'blank': 'Recenzent musí být vybrán'}, help_text='Vyberte uživatele, který recenzi napsal.', on_delete=django.db.models.deletion.CASCADE, related_name='recenze', to=settings.AUTH_USER_MODEL, verbose_name='Recenzent'),
        ),
    ]
