# Generated by Django 5.2.11 on 2026-03-04 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0009_vypujcka_ctenar_to_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vypujcka',
            name='ctenar',
            field=models.ForeignKey(error_messages={'blank': 'Čtenář musí být vyplněn.'}, help_text='Vyberte čtenáře (uživatele), ideálně ze skupiny readers.', limit_choices_to={'groups__name': 'readers'}, on_delete=django.db.models.deletion.CASCADE, related_name='vypujcky', to=settings.AUTH_USER_MODEL, verbose_name='Čtenář'),
        ),
    ]
